#~>
from src.core.errors import BaseError


#<·
class TcTcfmtCreatorError(BaseError): ...

class TcTcfmtReaderError(BaseError): ...

class PropertyError(BaseError): ...

class TcFmtError(BaseError): ...
